name: Framework Detector
description: 'Re-Usable action to detect a framework'

runs:
  using: "composite"
  steps:
    - run: ls -la
      shell: bash
      
    - run: |
        if [[ -f "package.json" ]]; then
          echo "Package.json file exists. Running action."
        else
          echo "Package.json file does not exist."
        fi
      shell: bash
